# Site settings
title: Regolamento The Entropics
description: Il regolamento del gruppo "The Entropics"
email:
baseurl: ""
url: "http://rules.serben.tk"

collections:
  rules:
    output: false
  reviews:
    output: false

defaults:
  - scope:
      path: ""
    values:
      draft: false


# Build settings
markdown: kramdown
permalink: none